# Spring
spring.application.name: semkin-middle-service

# FlyWay
spring.flyway.url: jdbc:postgresql://localhost:5432/gpb-postgres
spring.flyway.user: postgres
spring.flyway.password: postgres
spring.flyway.locations: classpath:db/migration

# Datasource
spring.datasource.url: jdbc:postgresql://localhost:5432/gpb-postgres
spring.datasource.username: postgres
spring.datasource.password: postgres
