# Spring
spring.application.name: semkin-middle-service
server.port: 8082
backend.base-url: http://localhost:8080

# Datasource
spring.datasource.url: jdbc:postgresql://localhost:5432/gpb-postgres
spring.datasource.username: ${GPB_DB_USERNAME}
spring.datasource.password: ${GPB_DB_PASSWORD}

# FlyWay
spring.flyway.url: jdbc:postgresql://localhost:5432/gpb-postgres
spring.flyway.user: ${GPB_DB_USERNAME}
spring.flyway.password: ${GPB_DB_PASSWORD}
spring.flyway.locations: classpath:db/migration
